// app/api/products/route.ts
import { NextRequest, NextResponse } from "next/server";
import connectDB from "@/lib/mongodb";
import Product from "@/models/Product";
import mongoose from "mongoose"; // Needed to check valid ObjectIds

export async function GET(request: NextRequest) {
  try {
    await connectDB();

    const { searchParams } = new URL(request.url);
    const category = searchParams.get("category");
    const collection = searchParams.get("collection"); // NEW: Support collection filtering
    const featured = searchParams.get("featured");
    const search = searchParams.get("search");
    const limit = parseInt(searchParams.get("limit") || "20");
    const page = parseInt(searchParams.get("page") || "1");
    const skip = (page - 1) * limit;

    // Build query
    const query: any = { isActive: true };

    if (category) {
      // Find category by slug and get its name for matching
      const Category = (await import("@/models/Category")).default;
      const cat = await Category.findOne({ slug: category }).lean();
      if (cat) {
        query.category = cat._id;
      }
    }

    // NEW: Filter by collection tag
    if (collection) {
      query.collections = collection;
    }

    if (featured === "true") {
      query.isFeatured = true;
    }

    if (search) {
      query.$text = { $search: search };
    }

    // Execute query with population
    const products = await Product.find(query)
      .populate("category", "name slug")
      .sort(search ? { score: { $meta: "textScore" } } : { createdAt: -1 })
      .skip(skip)
      .limit(limit)
      .lean();

    const total = await Product.countDocuments(query);

    return NextResponse.json({
      products,
      pagination: {
        page,
        limit,
        total,
        pages: Math.ceil(total / limit),
      },
    });
  } catch (err) {
    console.error("[GET /api/products]", err);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}

export async function POST(request: NextRequest) {
  try {
    await connectDB();

    const Category = (await import("@/models/Category")).default;
    const body = await request.json();

    // Validate required fields
    const requiredFields = ["name", "category", "basePrice"];
    for (const field of requiredFields) {
      if (!body[field]) {
        return NextResponse.json(
          { error: `${field} is required` },
          { status: 400 }
        );
      }
    }

    // FIX: The frontend now sends the database _id directly! 
    let categoryId = body.category;

    // Fallback: If for some reason it's not a valid ID, try to find it by name
    if (!mongoose.Types.ObjectId.isValid(categoryId)) {
      const categoryDoc = await Category.findOne({ 
        name: { $regex: new RegExp(`^${body.category}$`, "i") } 
      });
      if (!categoryDoc) {
        return NextResponse.json(
          { error: `Category '${body.category}' does not exist.` },
          { status: 400 }
        );
      }
      categoryId = categoryDoc._id;
    }

    // Create the product
    const product = await Product.create({
      name: body.name,
      // Note: `slug` is now auto-generated by the pre('validate') hook in the model!
      description: body.description || "No description provided.",
      shortDescription: body.shortDescription,
      category: categoryId, // Pass the verified ObjectId
      collections: body.collections || [], // <-- NEW: Save collections!
      tags: body.tags || [],
      images: body.images || [],
      variants: body.variants || [],
      basePrice: body.basePrice,
      compareAtPrice: body.compareAtPrice,
      currency: body.currency || "USD",
      isFeatured: body.isFeatured || false,
      isActive: body.isActive !== undefined ? body.isActive : true,
      metaTitle: body.metaTitle,
      metaDescription: body.metaDescription,
    });

    // Populate category for response
    await product.populate("category", "name slug");

    return NextResponse.json({ product }, { status: 201 });
  } catch (err: any) {
    console.error("[POST /api/products] Error:", err.message);

    // Handle validation errors
    if (err.name === "ValidationError") {
      const errors = Object.values(err.errors).map((e: any) => e.message);
      return NextResponse.json(
        { error: "Validation failed", details: errors },
        { status: 400 }
      );
    }

    // Handle duplicate key errors (e.g., unique slug)
    if (err.code === 11000) {
      return NextResponse.json(
        { error: "Product with this slug already exists" },
        { status: 409 }
      );
    }

    return NextResponse.json(
      { error: err.message || "Internal server error" },
      { status: 500 }
    );
  }
}